name: Update data in database
# This workflow is triggered on pushes to master (when a PR is merged) that include changes in the app/data directory.
on:
	push:
		branches:
			- master
		paths: 
			- 'app/data/*'

jobs:
  build:
    name: Generate data and update db
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
			- uses: actions/checkout@v2
			- uses: actions/setup-python@v1
  		with:
    		python-version: '3.8' 
  			architecture: 'x64' 
			# should install pipenv
			- run: python my_script.py

