name: Update data in database
# This workflow is triggered on pushes to master (when a PR is merged) that include changes in the app/data directory.
#on:
#  push:
#    branches:
#      - master
#    paths: 
#      - 'app/data/*'
on: [push, pull_request]

jobs:
  build:
    name: Generate data and update db
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      #- uses: dschep/install-pipenv-action@v1
        with:
          python-version: '3.8.x'
          architecture: 'x64' # Optional - x64 or x86, defaults to x64
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

